version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["jquery"]


exclude_patterns = [
  "**/migrations/*"
]

[[analyzers]]
name = "test-coverage"
enabled = false
