[project]
name = "Western-Friend-website"
version = "0.1.0"
description = "A website for Western Friend (westernfriend.org), a Quaker publication that provides resources and support for Quaker communities and individuals seeking to live out their faith in the world."
readme = "README.md"
requires-python = ">=3.10"
license = {text="agpl-3.0-or-later"}
authors = [
    { name = "Brylie Christopher Oxley", email = "brylie@amble.fi" },
    { name = "Mary Klein", email = "editor@westernfriend.org" },
    { name = "Western Friend" },
    { name = "Western Friend Board" },
]
maintainers = [
    { name = "Brylie Christopher Oxley", email = "brylie@amble.fi" }
]
keywords = [
    "django",
    "wagtail",
    "website",
    "western-friend",
    "quaker",
    "quakerism",
    "quaker-faith",
    "quaker-history",
    "quaker-peace",
    "quaker-testimonies",
    "quaker-worship",
    "quaker-organizations",
    "quaker-meetings",
    "quaker-education",
    "quaker-activism",
    "quaker-ecumenism",
    "interfaith",
    "quaker-faith-and-practice",
    "quaker-friends",
    "quaker-ecology",
    "quaker-arts",
    "quaker-letters",
    "quaker-epistles",
    "quaker-archives",
    "quaker-philosophy",
    "quaker-philanthropy",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Wagtail",
    "Intended Audience :: Quakers",
    "Intended Audience :: Religion",
    "Intended Audience :: Education",
    "Intended Audience :: Activists",
    "Intended Audience :: Ecumenists",
    "Intended Audience :: Archivists",
    "Intended Audience :: Philanthropists",
    "Intended Audience :: Peace Activists",
    "Intended Audience :: Environmentalists",
    "Intended Audience :: Artists",
    "Intended Audience :: Writers",
    "Intended Audience :: Philosophers",
    "Intended Audience :: Historians",
    "Intended Audience :: Scholars",
    "Intended Audience :: Researchers",
    "Intended Audience :: Students",
    "Intended Audience :: Librarians",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: AGPL-3.0-or-later",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Religion",
    "Topic :: Religion :: Christianity",
    "Topic :: Religion :: Christianity :: Denominations and Sects",
    "Topic :: Religion :: Christianity :: Denominations and Sects :: Protestantism",
    "Topic :: Religion :: Christianity :: Denominations and Sects :: Protestantism :: Quakers",
    "Topic :: Religion :: Christianity :: Denominations and Sects :: Protestantism :: Quakers :: Friends",
    "Topic :: Religion :: Christianity :: Denominations and Sects :: Protestantism :: Quakers :: Friends :: Unprogrammed",
    "Topic :: Religion :: Religious Studies",
    "Topic :: Religion :: Religious Studies :: History",
    "Topic :: Religion :: Religious Studies :: Philosophy of Religion",
    "Topic :: Religion :: Religious Studies :: Sociology of Religion",
    "Topic :: Religion :: Religious Studies :: Comparative Religion",
    "Topic :: Religion :: Religious Studies :: Ecumenism",
    "Topic :: Religion :: Religious Studies :: Interfaith",
    "Topic :: Religion :: Religious Studies :: Quaker Studies",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker History",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Faith",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Testimonies",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Worship",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Organizations",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Meetings",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Education",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Activism",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Ecumenism",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Faith and Practice",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Friends",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Ecology",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Arts",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Letters",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Epistles",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Archives",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Philosophy",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Philanthropy",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Peace",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker Activism",
    "Topic :: Religion :: Religious Studies :: Quaker Studies :: Quaker History"
]
dependencies = [
    "arrow",
    "braintree",
    "django-crispy-forms",
    "django-registration",
    "django-flatpickr",
    "dj-database-url",
    "pandas",
    "psycopg2-binary",
    "python-dotenv",
    "tqdm",
    "django-timezone-field",
    "tzdata",
    "wagtail-color-panel",
    "django-storages",
    "boto3",
    "wagtailmedia",
    "wagtail",
    "django-extensions",
    "django-stubs",
    "django",
]

[project.urls]
Homepage = "https://westernfriend.org"
Repository = "https://github.com/WesternFriend/WF-website"


[project.optional-dependencies]
dev = [
    "django-browser-reload",
    "pre-commit",
    "django-debug-toolbar",
    "coverage",
    "pre-commit",
    "black",
    "pandas-stubs",
    "types-requests",
    "types-beautifulsoup4",
    "coverage",
    "validate-pyproject",
]

[tool.black]
target-version = ['py311']

[tool.django-stubs]
django_settings_module = "core.settings.base"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[[tool.mypy.overrides]]
module = "wagtail.*"
ignore_missing_imports = true

[tool.ruff]
# Same as Black.
line-length = 88

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "**/migrations"
]

# Assume Python 3.11
target-version = "py311"
